### ISSUE TITLE
What even?

### ISSUE THREAD

**Issue by machinelearnedindividual** [SsnL/poisson_quasimetric_embedding#1]
I am honestly at a loss for words on this one. This whole repo is presented as being good and is just completely riddled with errors. That's not even mentioning the terribly inconsistent coding standards. If you are making a repo public you should put more effort into it to allow for others to be able to read your code and actually comprehend what is going on instead of it looking like it was hastily put together the night before the due date of a freshman coding project so as to not waste their time.

**Comment by SsnL** [comment]
thanks for the laugh. but no trolling. :)
